// import './globals.css'
import Navbar from '@/(components)/navbar/navbar';
import style from '@/style/home/homeScreen.module.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  let date =  new Date();
  let year = date.getFullYear();

  return (
    <html lang="en">
      <body>
        {/* <Navbar/> */}
        {children}
        {/* <div className={style.footerBlack}>
          <p className={style.footerText}>{`©${year} Appears Interior Studio Inc. `}</p>
        </div> */}
      </body>
    </html>
  )
}
